### ISSUE TITLE
open graph for facebook doesn't work

### ISSUE THREAD

**Issue by ARTIS-MEDIA** [JoomGalleryfriends/JoomGallery#104]
Hello. Open graph for facebook doesn't work. How to fix it?

**Comment by Elfangor93** [comment]
We had that topic already discussed in our forum:
http://www.forum.joomgalleryfriends.net/forum/index.php?thread/225-photos-don-t-load-on-facebook/

Are you able to solve the problem with this forumd discussion?

**Comment by ARTIS-MEDIA** [comment]
Why don't you issue a patch, but everyone who realizes that they have a problem has to write to you and fix it manually?

**Comment by Elfangor93** [comment]
Why dont **you** issue the patch?

JoomGallery is an OpenSource project - means that users develop for users. If you need a specific feature you can develop the feature by yourself and send a pull request to the project. JoomGalleryfirends will review your changes and include the changes afterwards to the next release. The other posibility is to open an issue and hope that another JoomGallery user develop that feature for you.

https://www.en.joomgalleryfriends.net/opensource.html
