### ISSUE TITLE
Warning during installation: failed to load external entity

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JoomGallery#108]
After merging the PR ['imgProcess-settings-cp'](https://github.com/JoomGalleryfriends/JoomGallery/pull/107) during a new installation the following warning appears:

Warning: simplexml_load_file(): I/O warning : failed to load external entity "...administrator/components/com_joomgallery/joomgallery.xml" in .../script.php on line 64

Joomla 3.10.6
PHP 8.0.10

**Comment by inLIMITit** [comment]
Hatte ich heute auch die Fehlermeldung. Habe die Komponente auf einer neuen Joomla 3 Installation neu installiert.
