### ISSUE TITLE
Image Upload failed but is succesfully uploaded

### ISSUE THREAD

**Issue by Tazzios** [JoomGalleryfriends/JoomGallery#122]
**Behavior**
I have some images that gives a 'Upload failed' error. However the image is succesfully uploaded

PHPlog
`PHP Warning:  Invalid argument supplied for foreach() in * \administrator\components\com_joomgallery\helpers\imgtools.php on line 3511`

It seems something related to the IPTC APP13 metadata.

ImageMagick 7.1.0-45 Q16-HDRI x64 e32676e:20220731 OR ImageMagick 6.9.10-68 Q16 x86_64 2021-10-13 
Joomgallery 3.60
Joomla 3.10.11

Image in question:
![5722239969_74ba95e0](https://user-images.githubusercontent.com/23451105/195030867-f1ddee6e-271e-4f60-809c-c66363f46d04.jpg)

**Comment by Elfangor93** [comment]
Have you tried already with GD as image processor?
Do you have the same error there?

**Comment by Tazzios** [comment]
Good idea:
Tested GD gives the same result.

**Comment by MrMusic** [comment]
Hi,

probably the php warning is causing the message.
The upload should work without 'error' messages if you set the 'Error Reporting' to None in the Joomla configuration.
PS: The 'orientation' tag seems to be missing in your image.

Regards
MrMusic

**Comment by Tazzios** [comment]
Thanks! the Error Reporting trick works.

Tested on 2 different joomla sites and hosting but on both was Error Reporting on (simple and max).

I also tried some resaving with xnview and paint before creating this issue but the metadata was not corrected/fixed.
