### ISSUE TITLE
Can't uninstall JoomGallery after updating to Joomla 4.3.0

### ISSUE THREAD

**Issue by Elfangor93** [JoomGalleryfriends/JoomGallery#128]
Found in the joomla.org forum:
https://forum.joomla.org/viewtopic.php?f=814&t=1001231

Seems like there is a problem with Joomla 4.3 and JoomGallery.Can anyone confitm that?

**Comment by MrMusic** [comment]
I have not tested it.
But JoomGallery 3.3.4 is outdated and cannot work with Joomla 4.x. Probably the 'uninstall' in the script.php would have to be adjusted.

**Comment by Elfangor93** [comment]
You are right havent seen that he uses such an old version...
