### ISSUE TITLE
Read more in the frontend upload

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JoomGallery#33]
Since https://github.com/JoomGallery/JoomGallery/pull/116 it is possible to insert 'Read more' link in image description.
Upload in the frontend: When clicking on the 'Read more' button, the `'<hr id="system-readmore" />'` is always inserted in the first tab, even if you are e.g. at Drag'N'Drop or Batch upload.

**Comment by Erftralle** [comment]
Confirmed, see #38 for a fix.
