### ISSUE TITLE
PHP 7 Notice

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JoomGallery#4]
PHP Notice:  Undefined variable: msg in administrator/components/com_joomgallery/controllers/control.php on line 127

**Comment by Erftralle** [comment]
Please provide detailed information on how to reproduce the PHP notice.

**Comment by MrMusic** [comment]
PHP Version 7.2:
Im Kontrollzentrum der JoomGallery Start der Installation einer Erweiterung, die keine gültige xml-Datei enthält.
Die Installation wird abgebrochen und es erscheint eine Warnung.
Wenn in Zeile 112 der administrator/components/com_joomgallery/controllers/control.php `if(is_object($installer->manifest))` nicht erfüllt ist, ist die Variable msg nicht definiert.
Es sollte ausreichen z.B. `$msg = '';` in Zeile 108 oder 111 einzufügen, um die PHP notice zu verhindern.
