### ISSUE TITLE
Language override of the toplist bar not possible

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JoomGallery#46]
A language override of the toplist bar does not work properly when Joomla SEF is enabled.
See [forum](https://www.forum.joomgalleryfriends.net/forum/index.php?thread/122-display-all-images-from-all-categories/&postID=527#post527) for more informations.

**Comment by Erftralle** [comment]
Please check #48 .

**Comment by MrMusic** [comment]
Thank you very much!
