### ISSUE TITLE
Google Maps in detail view is not GDPR compliant

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JoomGallery#47]
The integration of Google maps currently is not GDPR compliant.
The map should be loaded only after the user has actively agreed.
Is this a possible solution here?: https://github.com/01-Scripts/2Click-Iframe-Privacy
It would be important to be able to save the selection for the duration of the session so that the same query does not appear again for each image.
Can this solution be adopted?

**Comment by Elfangor93** [comment]
I like the way how it is solved in our forum-software:
https://www.forum.joomgalleryfriends.net/index.php?article/5-forum-als-webapp-auf-deinem-smartphone

There you see, where the content is referring to and you are able to follow the url to the source without embedding the content into the original website. If you click to embedd the source, there is no cookie set but your decision is saved serverside in your session. When storing the decision in a cookie I guess you will need a cookie hint...

**Comment by Erftralle** [comment]
> Is this a possible solution here?: https://github.com/01-Scripts/2Click-Iframe-Privacy

I just had a quick look at the solution presented there, I think it cannot be used (correct me if I am wrong). The prerequisite for it's use would be the direct use of an iframe, but JoomGallery uses the JavaScript API.

@Elfangor93's suggestion seems to work similarly, if I'm not wrong.

**Comment by MrMusic** [comment]
>If you click to embedd the source, there is no cookie set but your decision is saved serverside in your session...

Sounds good.


>...but JoomGallery uses the JavaScript API

You're right. JoomGallery uses Javascript. See
https://github.com/JoomGalleryfriends/JoomGallery/blob/06c4a84eee3c442179a4e4c681e7dbb566bc0067/components/com_joomgallery/views/detail/view.html.php#L872
and
https://github.com/JoomGalleryfriends/JoomGallery/blob/06c4a84eee3c442179a4e4c681e7dbb566bc0067/components/com_joomgallery/views/detail/tmpl/default.php#L419-L433

I think we should prevent these Javascript from running in a similar way as the iframe in https://github.com/01-Scripts/2Click-Iframe-Privacy.
Does anyone have a suggestion to solve the problem?

**Comment by Erftralle** [comment]
> Does anyone have a suggestion to solve the problem?

Please have a look at #50.
