### ISSUE TITLE
PHP 8: Error creating main category

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JoomGallery#59]
When using PHP 8.0 it is not possible to create 'main' categories.
Error Message: Invalid parent category ID:
It affects in frontend, backend and plugin JoomAutoCat

**Comment by wall007** [comment]
PHP 8.0 changed the behavior of string to number comparison.
https://www.php.net/manual/de/migration80.incompatible.php

In administrator/components/com_joomgallery/models/category.php:204 the parent_id is checked against '0', when the parent_id is not set this statement was true in PHP7 and is now false in PHP8.
We can change the line from
if($data['parent_id'] == 0)
to
if($data['parent_id'] == 0 or $data['parent_id'] == "")
as a simple hotfix. This will cover the case where the parent_id is the number '0' and where the parent_id is not set. 

It would be advisable to check the code for further occurrences of this problem.

**Comment by MrMusic** [comment]
Thank you @wall007 for the suggestion. It works very well.
Do you have a suggestion how to solve this problem in the plugin [JoomAutoCat](https://github.com/JoomGalleryfriends/JoomAutoCat)?

**Comment by wall007** [comment]
The $category object is not initialized in the _createCategory function.
Simply initialize the object with $category = new stdClass();

**Comment by MrMusic** [comment]
@wall007 it works great. Thanks a lot!
Should I open a pull request or do you want to do that?
