### ISSUE TITLE
404 with serf on

### ISSUE THREAD

**Issue by Sdemk** [JoomGalleryfriends/JoomGallery#77]
In view image i have 404
![immagine](https://user-images.githubusercontent.com/81992110/113619760-adf98a00-9659-11eb-8d3f-42f5febac9ae.png)

![immagine](https://user-images.githubusercontent.com/81992110/113619897-dda89200-9659-11eb-8529-8af258edeb7a.png)

But image exists. 
If I disable the serf everything works

You can help me please?

**Comment by MrMusic** [comment]
Probably a problem with the system plugin by a third-party extension.
See [here](https://www.en.joomgalleryfriends.net/detail-and-original-images-are-not-displayed.html) for more information.

**Comment by Elfangor93** [comment]
@Sdemk Can we close this issue?
