### ISSUE TITLE
Generation of animated thumbnails does not work

### ISSUE THREAD

**Issue by ClipartsFree** [JoomGalleryfriends/JoomGallery#88]
Hello,

after update to version 3.5.0 the generation of animated thumbnails does not work.

Example:

Link to original image: https://www.clipartsfree.de/images/joomgallery/details/gifs_129/kindernamen_271/schoene_jungennamen_273/vornamen_fuer_jungen_mit_a_281/arthur_jungenname_-_animierte_namen_im_gif-format_20210814_1719722103.gif

Link to generated Thumbnail: https://www.clipartsfree.de/images/joomgallery/thumbnails/gifs_129/kindernamen_271/schoene_jungennamen_273/vornamen_fuer_jungen_mit_a_281/arthur_jungenname_-_animierte_namen_im_gif-format_20210814_1719722103.gif

Bevor (while use of the previous version) it worked very well. Do you have any idea how to fix this bug?

**Comment by Elfangor93** [comment]
Animated GIFs in Thumbnails were removed with the new JoomIMGtools.
https://github.com/JoomGalleryfriends/JoomGallery/pull/35

It there really a need for animated thumbnails?

**Comment by ClipartsFree** [comment]
Hello Elfangor93, 

this really pity! That was really a cool functionality. It gives a possibility to user to see a small preview what exactly a gif animation is hidden behind a thumb. Just compare:

Category with animated thumbnails: https://en.clipartsfree.de/clipart-pictures-gallery/school-enrollment.html 

Category without animated thumbnails: https://www.clipartsfree.de/clipart-bilder-galerie/vornamen-fuer-maedchen-mit-a.html 

It a makes a difference! 

Can you please tell me how can I modify a code and put this functionality into the version 3.5.0 by myselves?

**Comment by Elfangor93** [comment]
For my taste I like the category view without animations better. A category view with animated GIFs looks very disturbing and unprofessional.
But it looks like as if this is a matter of taste...

Maybe you could start a PR to v3.6.1 to add a configuration paramter to enable/disable animation in thumbnails view.

The important places in the code to change are...

- Image uplods (upload form) https://github.com/JoomGalleryfriends/JoomGallery/blob/f9a5fa97194e223e06ddee66a6c79be07e9f4f48/administrator/components/com_joomgallery/helpers/upload.php#L2121
- Replace image (image form) https://github.com/JoomGalleryfriends/JoomGallery/blob/f9a5fa97194e223e06ddee66a6c79be07e9f4f48/administrator/components/com_joomgallery/models/image.php#L554
- Recreate images (category view) https://github.com/JoomGalleryfriends/JoomGallery/blob/f9a5fa97194e223e06ddee66a6c79be07e9f4f48/administrator/components/com_joomgallery/models/images.php#L736
- Rotate images (category view) https://github.com/JoomGalleryfriends/JoomGallery/blob/f9a5fa97194e223e06ddee66a6c79be07e9f4f48/administrator/components/com_joomgallery/models/images.php#L982
- Migration script (migration manager) https://github.com/JoomGalleryfriends/JoomGallery/blob/f9a5fa97194e223e06ddee66a6c79be07e9f4f48/administrator/components/com_joomgallery/helpers/migration.php#L1728

To preserve animation, you need to change 13th (last) argument in the method-call JoomIMGtools::resizeImage() to true.

**Comment by ClipartsFree** [comment]
1. You are right. This is a matter "of taste". For me gallery looks better
when you have beautiful static thumbs. In terms of SEO that is better too.

But this not realy user friendly for a user. He is looking for a concrete
animation and don't want to make 10-20 clicks to see how they all look like
within detail view. Better to get a full rubric overview and reach a target
within one single click.

2. Regarding development. As mentioned I am not a software developer, I am
an cartoon illustrator )) I do html/css simple php, sql and javascript
changes but not more.

Within last years I collected a lot of expirience by use of JoomGallery and
can provide your community with some ideas for improvement of SEO, mobile
design and new features.

3. Is a simple way in place to enable animated thumbnails witin 3.5.0
version?

Elfangor ***@***.***> schrieb am So., 15. Aug. 2021, 11:28:

**Comment by ClipartsFree** [comment]
@Elfangor93  For first thank you to your replies and advising. I changed within the file

JoomGallery/administrator/components/com_joomgallery/helpers/migration.php 

the code as following

`        $result['thumb'] = JoomIMGtools::resizeImage( $debugoutput,
                                                      $neworigimage,
                                                      $newthumbnail,
                                                      $this->_config->get('jg_useforresizedirection'),
                                                      $this->_config->get('jg_thumbwidth'),
                                                      $this->_config->get('jg_thumbheight'),
                                                      $this->_config->get('jg_thumbcreation'),
                                                      $this->_config->get('jg_thumbquality'),
                                                      $this->_config->get('jg_cropposition'),
                                                      $angle,
                                                      $autorot_thumb,
                                                      false,
                                                      true
                                                    );`

Afterwards I recreated thumbs and uploaded some new images. Unfortunatelly it does not work.

**Comment by ClipartsFree** [comment]
P. S. I got it! Thanks for your support! 

https://www.clipartsfree.de/clipart-bilder-galerie/vornamen-fuer-maedchen-mit-a.html 

Information to all JoomGallery useres/admins. The changes of the attribute have to be made within all five files!

**Comment by MrMusic** [comment]
>Within last years I collected a lot of expirience by use of JoomGallery and
can provide your community with some ideas for improvement of SEO, mobile
design and new features.

You are welcome to post your ideas and suggestions in the JoomGallery forum.

**Comment by ClipartsFree** [comment]
Hello dear all, 

inbetween I have got a new question. I would like to get sorted images in each category by number of views descending. Images with the highest number of views on top and images with lower number of views below. Can you please provide information which file and code have to be changed?

**Comment by MrMusic** [comment]
Hi,

>I would like to get sorted images in each category by number of views descending...

for sorting images there are two ways:

1. User decide
You could let the user decide how the images should be sorted. 
For this you would have to activate the following option in the configuration manager:
Category View >> General Settings >> User specified Category Order

2. Change the default sorting
Normally this option defines how the images should be sorted by default in the configuration manager:
Frontend Settings >> Image ordering

However, there is no option to sort by hits, this would have to be added. For example Add 
_$picorder[] = JHTML::_('select.option', JoomConfig::getValidImageSortingOrderByClauses(6), JText::_('Hits_ASC'));
$picorder[] = JHTML::_('select.option', JoomConfig::getValidImageSortingOrderByClauses(7), JText::_('Hits_DESC'));_
in administrator/components/com_joomgallery/views/config/tmpl/default.php after line 431
and 
in administrator/components/com_joomgallery/helpers/config.php 
change line 355 to
_private static $_validImageSortingOrderByClauses = array('ordering ASC', 'ordering DESC', 'imgdate ASC', 'imgdate DESC', 'imgtitle ASC', 'imgtitle DESC', 'hits ASC', 'hits DESC');_

**Comment by ClipartsFree** [comment]
Hello Mr. Music, thank you!

**Comment by Elfangor93** [comment]
How do you call this script?
Are the constats from JoomGallery (e.g _JOOM_TABLE_IMAGES) defined at that moment?
If yes, does the query work if you apply it with phpmyadmin?
What does the error message look like?

**Comment by ClipartsFree** [comment]
`How do you call this script? Are the constats from JoomGallery (e.g _JOOM_TABLE_IMAGES) defined at that moment?`

This is exactly the question, how exactly to do that on right way? I did it right simple:

a. mysql_connect (...)
b. public function optimize(...) {as described above}

The script is called via direct link .../.../optimization_script.php 

`What does the error message look like?`

Just simple 500 error in browser.

**Comment by Elfangor93** [comment]
Please post the php error that is thrown within the 500er request.

Are you calling the script within joomla?
The joomla framework must be loaded that you can use the JDatabase object from joomla.

**Comment by ClipartsFree** [comment]
Hi, thanks for your feedback!

After several experiments to do it via PHP I decided to solve this issue by setup of two permanent jobs within MyPhpAdmin (repair and optimize SQL statements). This information could be usefull for all JoomGallery users.

**Comment by ClipartsFree** [comment]
Hello dear All,

the following issue: I would like to generate for each search keyword an original URL.

For example:

Keyword "Haus"
URL something like this: https://www.malvorlagenkostenlos.com/ausmalbilder-gratis/index.php?view=search/keyword?=haus

Keyword "Auto"

URLsomething like this : https://www.malvorlagenkostenlos.com/ausmalbilder-gratis/index.php?view=search/keyword?=auto

How it is possible to realize?

**Comment by togo-de** [comment]
Hi,
try https://www.malvorlagenkostenlos.com/ausmalbilder-gratis/search?sstring=haus

regards

**Comment by ClipartsFree** [comment]
@togo-de: Danke schön! ))

**Comment by Elfangor93** [comment]
@ClipartsFree Can we close this issue?

**Comment by ClipartsFree** [comment]
Yes, please!
Thanks for your support!
